"use client";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { EventContext } from "./context/EventContext";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
});

// export const metadata = {
//   title: "Ticket Marketplace",
//   description: "Generated by create next app"
// };

const events = [
  {
    id: 1,
    name: "FC Barcelona vs Real Madrid — El Clásico",
    price: 150,
    isPast: false,
    location: "Santiago Bernabéu Stadium, Madrid, Spain",
    date: "10/26/2025",
    tickets: "1500 / 1500 available",
    description:
      "Experience the iconic El Clásico between FC Barcelona and Real Madrid, one of the biggest football rivalries in the world. Don't miss this epic showdown!",
    image: "/images/event1.jpg"
  },
  {
    id: 2,
    name: "FC Barcelona vs Paris Saint‑Germain",
    price: 130,
    isPast: false,
    location: "Estadi Olímpic Lluís Companys, Barcelona, Spain",
    date: "10/01/2025",
    tickets: "1200 / 1200 available",
    description:
      "UEFA Champions League clash as Barcelona hosts PSG. Watch world-class stars battle it out on the field!",
    image: "/images/event2.png"
  },
  {
    id: 3,
    name: "Argentina vs France — International Friendly",
    price: 140,
    isPast: false,
    location: "Lusail Stadium, Lusail, Qatar",
    date: "03/28/2026",
    tickets: "800 / 800 available",
    description:
      "An international friendly match between Argentina and France, featuring star players from both teams. Exciting football guaranteed!",
    image: "/images/event3.jpg"
  },
  {
    id: 4,
    name: "Argentina vs Portugal — World Cup Qualifier",
    price: 135,
    isPast: true,
    location: "Estadio Monumental, Buenos Aires, Argentina",
    date: "11/15/2025",
    tickets: "900 / 900 available",
    description:
      "A blockbuster World Cup qualifying match featuring Argentina and Portugal. Catch the action live at the stadium!",
    image: "/images/event4.jpg"
  }
];


export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <EventContext.Provider value={events}>
        <Header />
          {children}
        <Footer />
        </EventContext.Provider>
      </body>
    </html>
  );
}
